# Generated by Django 5.2.1 on 2025-05-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ad_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('electronics', 'Электроника'), ('books', 'Книги'), ('clothes', 'Одежда'), ('home', 'Товары для дома'), ('sport', 'Спорт'), ('other', 'Другое')], max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='condition',
            field=models.CharField(choices=[('new', 'Новый'), ('used', 'Б/у'), ('good', 'В хорошем состоянии'), ('fair', 'Удовлетворительное')], max_length=50, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Объявление создано'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на изображение'),
        ),
    ]
